require 'motion_build/rule'
require 'motion_build/file_rule'

require 'motion_build/rules/object_file_rule'
require 'motion_build/rules/multifile_rule'
require 'motion_build/rules/emit_llvm_bitcode_rule'
require 'motion_build/rules/parse_llvm_bitcode_rule'
require 'motion_build/rules/assemble_source_rule'
require 'motion_build/rules/lipo_rule'
require 'motion_build/rules/copy_file_rule'
require 'motion_build/rules/unlink_file_rule'
require 'motion_build/rules/compile_ruby_source_rule'
require 'motion_build/rules/build_project_rule'
require 'motion_build/rules/render_erb_file_rule'
require 'motion_build/rules/compile_clang_source_rule'
require 'motion_build/rules/prepare_bundle_rule'
require 'motion_build/rules/link_objects_rule'
require 'motion_build/rules/render_plist_rule'
